### ISSUE TITLE
feature request: allow to add custom content to buttons

### ISSUE THREAD

**Issue by st-h** [shipshapecode/ember-shepherd#303]
I was trying to add arrows from the [font awesome](https://github.com/FortAwesome/ember-fontawesome) library to the next and back buttons. In the end I was able to accomplish this by adding :before and :after elements that contain the svg data as css property `content: url('data:image/svg+xml; utf8, <svg....`

However, this is not only a quite inconvenient way to do this, this also has the drawback of not being able to add `:hover` styles as it is not possible to [change the fill color of the svg](https://stackoverflow.com/a/21882857). 

It would be awesome if there would be a way to add other content than just the text of the button

**Comment by rwwagner90** [comment]
So a couple things, `text` supports HTML https://github.com/shipshapecode/shepherd/blob/3dee64d023e9545f61d508b36d030a331b5e0049/src/js/step.js#L129

You can add that svg code in the text if you would like or use the font awesome font, rather than the svgs.

Also, you can definitely change the fill and stroke of svgs on hover, I do it for my icons all the time. Something like this:

```scss
svg {
          path {
            fill: $gold;
            transition-duration: 0.25s;
            transition-property: fill;
          }

          &:hover {
            path {
              fill: $grey-transparent;
            }
          }
        }
```

Hopefully one of those methods works for you!
